import { Router } from "express";

import { AisleRoutes } from "../module/aisle/aisle.route.js";
import { AuthRoutes } from "../module/auth/auth.route.js";
import { BinRoutes } from "../module/bin/bin.route.js";
import { BrandRoutes } from "../module/brand/brand.route.js";
import { CategoryRoutes } from "../module/category/category.route.js";
import { InventoryRoutes } from "../module/inventory/inventory.route.js";
import { NotificationRoutes } from "../module/notification/notification.route.js";
import { PackingRoutes } from "../module/packing/packing.route.js";
import { PickingRoutes } from "../module/picking/picking.route.js";
import { ProductRoutes } from "../module/product/product.route.js";
import { PurchaseOrderRoutes } from "../module/purchaseOrder/purchaseOrder.route.js";
import { SalesOrderRoutes } from "../module/salesOrder/salesOrder.route.js";
import { ShelfRoutes } from "../module/shelf/shelf.route.js";
import { ShippingRoutes } from "../module/shipping/shipping.route.js";
import { SupplierRoutes } from "../module/supplier/supplier.route.js";
import { UserRoutes } from "../module/user/user.route.js";
import { WarehouseRoutes } from "../module/warehouse/warehouse.route.js";
import { ZoneRoutes } from "../module/zone/zone.route.js";

const router = Router();
router.use("/auth", AuthRoutes);
router.use("/users", UserRoutes);
router.use("/warehouses", WarehouseRoutes);
router.use("/zones", ZoneRoutes);
router.use("/aisles", AisleRoutes);
router.use("/shelves", ShelfRoutes);
router.use("/bins", BinRoutes);
router.use("/categories", CategoryRoutes);
router.use("/brands", BrandRoutes);
router.use("/products", ProductRoutes);
router.use("/inventory", InventoryRoutes);
router.use("/suppliers", SupplierRoutes);
router.use("/purchase-orders", PurchaseOrderRoutes);
router.use("/sales-orders", SalesOrderRoutes);
router.use("/picking", PickingRoutes);
router.use("/packing", PackingRoutes);
router.use("/shipping", ShippingRoutes);
router.use("/notifications", NotificationRoutes);

export const IndexRoutes = router;
